### ISSUE TITLE
Grouping actions in controllers

### ISSUE THREAD

**Issue by tolemac** [ExplicitlyImplicit/AspNetCore.Mvc.FluentActions#2]
I would like grouping actions in controllers.

I have seen `.GroupBy(...)` method but I understand it can be used only for inspecting fluent action collection, but is not used to group actions in controllers.

When I use this config: 

```csharp
            app.UseFluentActions(
                actions =>
                {
                    actions.RouteGet("/hello/World").GroupBy("Group1").To(() => "hello world");
                    actions.RouteGet("/hello/World2").GroupBy("Group1").To(() => "hello world2");
                    actions.RouteGet("/bye/World").GroupBy("Group2").To(() => "bye bye world");
                    actions.RouteGet("/bye/World2").GroupBy("Group2").To(() => "bye bye world2");
                }
            );

```
4 controllers are generated, I would like to generate only 2 controller, one called `Group1Controller` and other called `Group2Controller`.

Swagger generate that:
![image](https://user-images.githubusercontent.com/247167/53959563-3f494b80-40e4-11e9-9487-0da6d51ed015.png)

It's uggly.

The question is ¿there are some way to group actions in controllers and set controller names?

**Comment by ExplicitlyImplicit** [comment]
Hi @tolemac thanks for submitting some feedback! Right now there is no support for what you are after but I have been experimenting with it before. I see how it is useful for autogenerating docs like swagger so I'll take another look at it!

**Comment by tolemac** [comment]
I have been thinking about something like that:

```csharp
app.UseFluentActions(
    actions =>
    {
        actions.Controller("Hello", controllerActions => {
            controllerActions.RouteGet("/hello/World").GroupBy("Group1").To(() => "hello world");
            controllerActions.RouteGet("/hello/World2").GroupBy("Group1").To(() => "hello world2");
        }).Authorize().WithAttribute<MyCustomAttribute>();
        
        actions.Controller("Bye", controllerActions => {
            controllerActions.RouteGet("/bye/World").GroupBy("Group2").To(() => "bye bye world");
            controllerActions.RouteGet("/bye/World2").GroupBy("Group2").To(() => "bye bye world2");
        }).WithAttribute<OtherAttributte>();
    }
);
```

Thanks ;)

**Comment by javiercampos** [comment]
It's easy to make Swagger tags (at least using `Swashbuckle`) for the actions... it'd be great if the actions were actually inserted on the group (for the API Explorer) when using `GroupBy()`, if so, it'd be a matter of using:
```
services.AddSwaggerGen(act =>
{
    act.TagActionsBy(api => new[] { api.GroupName });
    /* etc */
});
```
But otherwise, you have the whole `ApiDescription` there so you can maintain a dictionary with a list of tags (or "controllers") for each route/method and specify it there.

**Comment by tolemac** [comment]
@ExplicitlyImplicit as @javiercampos says, Is not necessary to make changes, I can group actions using my own attributes and obtain it from api explorer.

For example:
```csharp
public class MyGroupAttribute: Attribute
{
    public string GroupName { get; }
    public MyGroupAttribute(string groupName)
    {
        GroupName = groupName;
    }
}
....
....
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new Info { Title = "Test API", Version = "v1" });
    c.TagActionsBy(apiDesc => !apiDesc.TryGetMethodInfo(out var mi) ? new[] {apiDesc.GroupName} : new[] {mi.GetCustomAttribute<MyGroupAttribute>()?.GroupName ?? mi.Name});
    
});

...
...
...

app.UseFluentActions(
    actions =>
    {
        actions.RouteGet("/hello/World")
            .WithCustomAttributeOnClass<MyGroupAttribute>(new[] {typeof(string)}, new []{"Group1"})
            .To(() => "hello world");
        actions.RouteGet("/hello/World2")
            .WithCustomAttributeOnClass<MyGroupAttribute>(new[] {typeof(string)}, new []{"Group1"})
            .To(() => "hello world2");
        actions.RouteGet("/bye/World")
            .WithCustomAttributeOnClass<MyGroupAttribute>(new[] {typeof(string)}, new []{"Group2"})
            .To(() => "bye bye world");
        actions.RouteGet("/bye/World2")
            .WithCustomAttributeOnClass<MyGroupAttribute>(new[] {typeof(string)}, new []{"Group2"})
            .To(() => "bye bye world2");
    }
);
```

Now shagger ui shows:
![image](https://user-images.githubusercontent.com/247167/54262240-03900500-456e-11e9-81b5-80574a96aacd.png)

It's ok for me.

**Comment by tolemac** [comment]
In addition, I would like to know what do "GroupBy" method.

I can see on `FluentAction.cs` the method:

```csharp
public virtual FluentAction<TP, TR> GroupBy(string groupName)
{
    Definition.GroupName = groupName;
    return this;
}
```

However `GroupName` member in `FluentActionDefinition` is not used on building process.

I'm wrong?


Thanks ;)

**Comment by ExplicitlyImplicit** [comment]
It's great that you've found ways to solve it @tolemac @javiercampos. Like you said @tolemac, groups are not used internally, it was added for external use, use cases just like this one. I agree it would be nice to add some more identifiable data for actions in a group (maybe add an attribute on the class?) so you could use it better.

I don't want to add swagger as a dependency to this project but better swagger integration is definitely desirable so I'll take another look at it.
